apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: vineyard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana-oss:latest
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vineyard-secrets
              key: GRAFANA_PASSWORD
        - name: GF_USERS_ALLOW_SIGN_UP
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: vineyard
spec:
  type: NodePort # Allowing external access for dashboard viewing
  ports:
  - port: 3000
    nodePort: 30000
  selector:
    app: grafana
