apiVersion: v1
kind: Secret
metadata:
  name: vineyard-secrets
  namespace: vineyard
type: Opaque
data:
  # Base64 encoded values
  POSTGRES_PASSWORD: cGFzc3dvcmQ= # password
  INFLUXDB_ADMIN_TOKEN: YW5hbHl0aWNzLXRva2VuLWRldg== # analytics-token-dev
  GRAFANA_PASSWORD: YWRtaW4= # admin
