server:
  port: 8084

spring:
  application:
    name: device-service

  # Configuração do PostgreSQL
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/smart_vineyard}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  # Configuração do JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Logging
logging:
  level:
    com.vineyard.device: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
